### First request
curl -X POST -d name="juma" -d address="hakkila" http://localhost:8000/addresses

### Second request
curl -X POST -d name="ali" -d address="kerava" http://localhost:8000/addresses

### Third request
curl -X POST -d name="john" -d address="espoo" http://localhost:8000/addresses

### Fourth request
curl -X POST -d name="maria" -d address="vantaa" http://localhost:8000/addresses


### 

### GET request for one address
curl -X GET "http://localhost:8000/"






